# Generated by Django 5.2.7 on 2025-10-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placeimage',
            name='url',
        ),
        migrations.AddField(
            model_name='placeimage',
            name='image',
            field=models.ImageField(default='your_default_image_url.jpg', upload_to='places/'),
            preserve_default=False,
        ),
    ]
